export const  calendar = {
  years : [
    2018,
    2019,
    2020,
    2021,
    2022,
  ],
  weeks : [
    {value: 'Monday', name: 'Mn'},
    {value: 'Tuesday', name: 'Tn'},
    {value: 'Wednesday', name: 'We'},
    {value: 'Thursday', name: 'Th'},
    {value: 'Friday', name: 'Fi'},
    {value: 'Saturday', name: 'Sa'},
    {value: 'Sunday', name: 'Su'},
  ],
  days : [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
  ],
  months : [
    { value: 'January'},
    { value: 'February'},
    { value: 'March'},
    { value: 'April'},
    { value: 'May'},
    { value: 'June'},
    { value: 'July'},
    { value: 'August'},
    { value: 'September'},
    { value: 'October'},
    { value: 'November'},
    { value: 'December'},
  ],
};
